blog/urls.py
from django.urls import path
from django.views.decorators.cache import never_cache
from blog.apps import BlogConfig
from blog.views import *

app_name = BlogConfig.name

urlpatterns = [
    path('', BlogListView.as_view(), name='home'),
    path('<slug:slug>/', BlogDetailView.as_view(), name='blog_detail'),
    path('blog/form/', never_cache(BlogCreateView.as_view()), name='blog_form'),
    path('blog/update/<int:pk>/', never_cache(BlogUpdateView.as_view()), name='blog_update'),
    path('blog/delete/<int:pk>/', BlogDeleteView.as_view(), name='blog_confirm_delete')
]

config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('catalog/', include('catalog.urls', namespace='catalog')),
    path('users/', include('users.urls', namespace='users')),
    path('', include('blog.urls', namespace='blog'))
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/models.py
from django.db import models
from django.urls import reverse


NULLABLE = {'blank': True, 'null': True}


class Blog(models.Model):
    title = models.CharField(max_length=150, verbose_name='Заголовок')
    slug = models.SlugField(max_length=150, verbose_name='Человекопонятный URL', **NULLABLE)
    content = models.TextField(verbose_name='Содержимое')
    image = models.ImageField(upload_to='blog/', verbose_name='Изображение', **NULLABLE)
    create_date = models.DateField(verbose_name='Дата создания')
    is_published = models.BooleanField(default=True, verbose_name='Опубликован')
    count_of_view = models.PositiveIntegerField(default=0, verbose_name='Количество просмотров')

    def delete(self, *args, **kwargs):
        self.is_published = False
        self.save()

    def __str__(self):
        return f'{self.title}'

    def increase_count_of_view(self):
        self.count_of_view += 1
        self.save()

    def get_absolute_url(self):
        return reverse('blog_detail', kwargs={'slug': self.slug})

    class Meta:
        verbose_name = 'новость'
        verbose_name_plural = 'новости'
        ordering = ('title',)

blog/views.py
from django.contrib.auth.mixins import LoginRequiredMixin, PermissionRequiredMixin
from django.urls import reverse_lazy, reverse
from django.views import generic
from django.utils.text import slugify
from transliterate import translit
from blog.models import Blog


class BlogListView(generic.ListView):
    model = Blog
    extra_context = {
        "title": "Новости дня"
    }

    def get_queryset(self):
        queryset = super().get_queryset()
        queryset = queryset.filter(is_published=True)
        return queryset


class BlogDetailView(generic.DetailView):
    model = Blog

    def get_context_data(self, **kwargs):
        context_data = super().get_context_data(**kwargs)
        return context_data

    def get_object(self, queryset=None):
        object_item = super().get_object(queryset)
        object_item.increase_count_of_view()
        object_item.save()
        return object_item


class BlogCreateView(LoginRequiredMixin, PermissionRequiredMixin, generic.CreateView):
    model = Blog
    fields = ('title', 'content', 'image', 'create_date')
    success_url = reverse_lazy('blog:home')
    permission_required = 'blog.add_blog'

    def form_valid(self, form):
        post = form.save(commit=False)
        eng_title = translit(post.title, 'ru', reversed=True)
        post.slug = slugify(eng_title, allow_unicode=True)
        return super(BlogCreateView, self).form_valid(form)


class BlogUpdateView(LoginRequiredMixin, PermissionRequiredMixin, generic.UpdateView):
    model = Blog
    fields = ('title', 'slug', 'content', 'image', 'create_date')
    permission_required = 'blog.change_blog'

    def get_success_url(self):
        return reverse('blog:blog_detail', kwargs={'slug': self.object.slug})


class BlogDeleteView(LoginRequiredMixin, PermissionRequiredMixin, generic.DeleteView):
    model = Blog
    success_url = reverse_lazy('blog:home')
    permission_required = 'blog.delete_blog'

    def get_queryset(self):
        queryset = super().get_queryset()
        queryset = queryset.filter(is_published=True)
        return queryset

blog/templates/blog/blog_confirm_delete.html
{% extends 'catalog/base.html' %}

{% block content %}
    <form class="obratnuj-zvonok" autocomplete="off" method='post'>
        {% csrf_token %}
        <div class="container">
            Уверены что хотите удалить новость {{ blog }}
            <input type="submit" class="btn btn-success" value="Уверен">
        </div>
    </form>
    <a href="{% url 'blog:home' %}" class="btn btn-secondary my-3"
       style="background: #0062cc">Назад</a>
{% endblock %}

blog/templates/blog/blog_detail.html
{% extends 'catalog/base.html' %}

{% block content %}
    {% load tags %}

    <div class="container">
        <div class="row featurette">
            <div class="col-md-7">
                <h2>{{ blog.title }}</h2>
                <p class="lead">{{ blog.content }}</p>
            </div>
            <div class="col-md-5">
                <img width="350" height="300" class="featurette-image img-fluid mx-auto" src="/media/{{ blog.image }}"
                     alt="Generic placeholder image">
            </div>
        </div>
    </div>
    <div>
        <a href="{% url 'blog:home' %}" class="btn btn-secondary my-3"
           style="background: #0062cc">Назад</a>
        {% if perms.blog.delete_blog %}
            <a href="{% url 'blog:blog_confirm_delete' blog.pk %}" class="btn btn-secondary my-3"
               style="background: red">Удалить</a>
        {% endif %}
    </div>
{% endblock %}

blog/templates/blog/blog_form.html
{% extends 'catalog/base.html' %}

{% block content %}
<form action="" method="post" enctype="multipart/form-data">
    <form class="obratnuj-zvonok" autocomplete="off" method='post'>
        {% csrf_token %}
        <div class="container">
            {{ form.as_p }}
            <input type="submit" class="btn btn-success" value="Сохранить">
        </div>
    <a href="{% url 'blog:home' %}" class="btn btn-secondary my-3"
       style="background: #0062cc">Назад</a>
    </form>
{% endblock %}

blog/templates/blog/blog_list.html
{% extends 'catalog/base.html' %}

{% block content %}
    {% for blog in blog_list %}
        {% include 'blog/includes/inc_blog_card.html' %}
    {% endfor %}
    {% if perms.blog.add_blog %}
        <a href="{% url 'blog:blog_form' %}" class="btn btn-secondary my-3"
           style="background: #0062cc">Создать</a>
    {% endif %}
{% endblock %}