blog/urls.py
from django.urls import path
from django.views.decorators.cache import never_cache
from blog.apps import BlogConfig
from blog.views import *

app_name = BlogConfig.name

urlpatterns = [
    path('', BlogListView.as_view(), name='home'),
    path('<slug:slug>/', BlogDetailView.as_view(), name='blog_detail'),
    path('blog/form/', never_cache(BlogCreateView.as_view()), name='blog_form'),
    path('blog/update/<int:pk>/', never_cache(BlogUpdateView.as_view()), name='blog_update'),
    path('blog/delete/<int:pk>/', BlogDeleteView.as_view(), name='blog_confirm_delete')
]

catalog/urls.py
from django.urls import path
from django.views.decorators.cache import cache_page, never_cache
from catalog.apps import CatalogConfig
from catalog.views import *


app_name = CatalogConfig.name

urlpatterns = [
    path('contacts/',never_cache(ContactCreateView.as_view()), name='contacts'),
    path('catalog/', ProductsListView.as_view(), name='catalog'),
    path('product_items/<int:pk>/', cache_page(60)(ProductDetailView.as_view()), name='product_items'),
    path('product/create/', never_cache(ProductCreateView.as_view()), name='save_product'),
    path('product/update/<int:pk>/', never_cache(ProductUpdateView.as_view()), name='product_form'),
    path('product/update_cutted/<int:pk>/', never_cache(ProductUpdateCuttedView.as_view()), name='product_form_cutted'),
    path('product/is_published/<int:pk>/', change_is_published, name='change_is_published'),
    path('category/', CategoryListView.as_view(), name='category')
]

config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('catalog/', include('catalog.urls', namespace='catalog')),
    path('users/', include('users.urls', namespace='users')),
    path('', include('blog.urls', namespace='blog'))
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
from django.contrib.auth.views import LoginView, LogoutView
from django.urls import path
from django.views.generic import TemplateView
from users.apps import UsersConfig
from users.views import ProfileUpdateView, RegisterView, EmailVerify, CustomPasswordResetView, \
    CustomPasswordResetConfirmView, CustomPasswordResetDoneView, CustomPasswordResetCompleteView

app_name = UsersConfig.name
urlpatterns = [
    path('', LoginView.as_view(template_name='users/login.html'), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('profile/', ProfileUpdateView.as_view(), name='profile'),
    path('register/', RegisterView.as_view(), name='register'),
    path('password/reset/', CustomPasswordResetView.as_view(template_name='users/password_reset_form.html'),
         name='password_reset'),
    path('confirm_email/', TemplateView.as_view(template_name='users/confirm_email.html'), name='confirm_email'),
    path('verify_email/<uidb64>/<token>/', EmailVerify.as_view(), name='verify_email'),
    path('invalid_verify/', TemplateView.as_view(template_name='users/invalid_verify.html'), name='invalid_verify'),
    path('password/reset/confirm/<uidb64>/<token>/', CustomPasswordResetConfirmView.as_view(),
         name='password_reset_confirm'),
    path('password/reset/done', CustomPasswordResetDoneView.as_view(), name='password_reset_done'),
    path('', CustomPasswordResetCompleteView.as_view(), name='password_reset_complete')
]

catalog/models.py
from django.db import models

from config import settings

NULLABLE = {'blank': True, 'null': True}


class Category(models.Model):
    name = models.CharField(max_length=150, verbose_name='Наименование')
    description = models.TextField(verbose_name='Описание')

    def __str__(self):
        return f'{self.name}'

    class Meta:
        verbose_name = 'категория'
        verbose_name_plural = 'категории'
        ordering = ('name',)


class Product(models.Model):
    name = models.CharField(max_length=150, verbose_name='Наименование')
    description = models.TextField(verbose_name='Описание')
    image = models.ImageField(upload_to='products/', verbose_name='Изображение', **NULLABLE)
    category = models.ForeignKey(Category, on_delete=models.CASCADE, verbose_name='Категория')
    price = models.IntegerField(verbose_name='Цена за покупку')
    created_date = models.DateField(verbose_name='Дата создания')
    changed_date = models.DateField(verbose_name='Дата последнего изменения')
    is_published = models.BooleanField(default=False, verbose_name='признак активности товара')
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.SET_NULL, **NULLABLE)

    def toggle_is_published(self):
        self.is_published = not self.is_published
        self.save()

    def __str__(self):
        return f'{self.name}'

    class Meta:
        verbose_name = 'продукт'
        verbose_name_plural = 'продукты'
        ordering = ('name',)
        permissions = [
            (
                'set_published_product',
                'Can publish product'
            ),
            (
                'can_edit_description_and_category_product',
                'Can edit description and category product'
            )
        ]


class Contact(models.Model):
    name = models.CharField(max_length=150, verbose_name='Имя пользователя')
    phone = models.CharField(max_length=20, verbose_name='Номер телефона')
    message = models.TextField(verbose_name='Сообщение')

    def __str__(self):
        return f'{self.name} - {self.phone}'

    class Meta:
        verbose_name = 'контакт'
        verbose_name_plural = 'контакты'
        ordering = ('name',)


class Version(models.Model):
    product = models.ForeignKey(Product, on_delete=models.CASCADE, verbose_name='Продукт')
    num_of_version = models.CharField(default=1, verbose_name='Номер версии')
    title = models.CharField(max_length=150, verbose_name='Название версии', **NULLABLE)

    is_active = models.BooleanField(default=True, verbose_name='признак текущей версии')

    def __str__(self):
        return f'{self.title} - {self.num_of_version} ({self.product})'

    class Meta:
        verbose_name = 'версия'
        verbose_name_plural = 'версии'

catalog/forms.py
from django import forms

from catalog.models import *

FORBIDDEN_WORDS = ['казино', 'криптовалюта', 'крипта', 'биржа', 'дешево', 'бесплатно', 'обман', 'полиция',
                   'радар']


class FormStyleMixin:
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'form-control'


class ProductForm(FormStyleMixin, forms.ModelForm):
    class Meta:
        model = Product
        exclude = ('user', 'is_published')

    def clean_name(self):
        cleaned_data = self.cleaned_data['name']
        if cleaned_data.lower() in FORBIDDEN_WORDS:
            raise forms.ValidationError(f"Нельзя вносить слово {cleaned_data}, замените его на другое")
        return cleaned_data

    def clean_description(self):
        cleaned_data = self.cleaned_data['description']
        if cleaned_data.lower() in FORBIDDEN_WORDS:
            raise forms.ValidationError(f"Нельзя вносить слово {cleaned_data}, замените его на другое")
        return cleaned_data


class ProductFormCutted(ProductForm, FormStyleMixin, forms.ModelForm):
    class Meta:
        model = Product
        fields = ('description', 'category')


class VersionForm(FormStyleMixin, forms.ModelForm):
    class Meta:
        model = Version
        fields = ('product', 'num_of_version', 'title',)

catalog/views.py
from django.contrib.auth.decorators import permission_required
from django.contrib.auth.mixins import PermissionRequiredMixin, LoginRequiredMixin
from django.forms import inlineformset_factory
from django.shortcuts import get_object_or_404, redirect
from django.urls import reverse_lazy, reverse
from django.views import generic

from catalog.forms import ProductForm, VersionForm, ProductFormCutted
from catalog.models import Product, Contact, Version, Category
from catalog.services.cashe import get_cache_categories


class CategoryListView(generic.ListView):
    model = Category
    queryset = get_cache_categories()

    def get_context_data(self, **kwargs):
        context_data = super().get_context_data(**kwargs)
        context_data['product_list'] = Product.objects.all()
        context_data['title'] = "Категории товаров"
        return context_data


class ProductsListView(generic.ListView):
    model = Product
    extra_context = {
        "title": "Каталог товаров"
    }


class ProductDetailView(generic.DetailView):
    model = Product

    def get_context_data(self, **kwargs):
        context_data = super().get_context_data(**kwargs)
        context_data['title'] = context_data['product']
        return context_data


class ContactCreateView(generic.CreateView):
    model = Contact
    fields = ('name', 'phone', 'message')


class ProductCreateView(LoginRequiredMixin, generic.CreateView):
    model = Product
    extra_context = {
        "title": "Внести новый товар"
    }
    form_class = ProductForm
    success_url = reverse_lazy('catalog:catalog')

    def form_valid(self, form):
        self.object = form.save()
        self.object.user = self.request.user
        self.object.save()
        return super().form_valid(form)


class ProductUpdateCuttedView(PermissionRequiredMixin, generic.UpdateView):
    model = Product
    template_name = 'catalog/product_form.html'
    form_class = ProductFormCutted
    permission_required = 'catalog.can_edit_description_and_category_product'

    def get_success_url(self):
        return reverse('catalog:product_items', kwargs={'pk': self.object.pk})


class ProductUpdateView(generic.UpdateView):
    model = Product
    template_name = 'catalog/product_form_with_formset.html'
    form_class = ProductForm

    def get_context_data(self, **kwargs):
        context_data = super().get_context_data(**kwargs)
        VersionFormset = inlineformset_factory(Product, Version, form=VersionForm, extra=1)

        if self.request.method == 'POST':
            context_data['formset'] = VersionFormset(self.request.POST, instance=self.object)

        else:
            context_data['formset'] = VersionFormset(instance=self.object)

        return context_data

    def form_valid(self, form):
        context_data = self.get_context_data()
        formset = context_data['formset']
        self.object = form.save()
        if formset.is_valid():
            formset.instance = self.object
            formset.save()
        return super().form_valid(form)

    def get_success_url(self):
        return reverse('catalog:product_items', kwargs={'pk': self.object.pk})


@permission_required('catalog.set_published_product')
def change_is_published(request, pk):
    product_item = get_object_or_404(Product, pk=pk)
    product_item.toggle_is_published()
    return redirect(reverse('catalog:product_items', args=[product_item.pk]))

catalog/templates/catalog/includes/inc_catalog_address.html
<a class="raw">
    {% if user.is_authenticated %}
    <a href="{% url 'users:logout' %}" class="btn" style="color: black">Выйти</a><br>
    <a href="{% url 'users:profile' %}" class="btn" style="color: black">Профиль</a>
    {% else %}
    <a href="{% url 'users:login' %}" class="btn" style="color: black">Войти</a><br>
    <a href="{% url 'users:register' %}" class="btn" style="color: black">Зарегистрироваться</a>
    {% endif %}
</a>

catalog/templates/catalog/includes/inc_catalog_footer.html
<footer class="pt-4 my-md-5 pt-md-5 border-top">
    <div class="row" style="margin: auto">
        <div class="col-12 col-md">
            SkyStore
            <small class="d-block mb-3 text-muted">&copy; 2023</small>
        </div>
        <div class="col-6 col-md">
            <h5>Категории</h5>
            <ul class="list-unstyled text-small">
                <li><a class="text-muted" href="#">Рассылки</a></li>
                <li><a class="text-muted" href="#">Телеграм боты</a></li>
                <li><a class="text-muted" href="#">Полезные утилиты</a></li>
                <li><a class="text-muted" href="#">Веб-приложения</a></li>
                <li><a class="text-muted" href="#">Микросервисы</a></li>
            </ul>
        </div>
        <div class="col-6 col-md">
            <h5>Дополнительно</h5>
            <ul class="list-unstyled text-small">
                <li><a class="text-muted" href="#">Мы пишем</a></li>
            </ul>
        </div>
        <div class="col-6 col-md">
            <h5>О нас</h5>
            <ul class="list-unstyled text-small">
                <li><a class="text-muted" href="#">Контакты</a></li>
            </ul>
        </div>
    </div>
</footer>

catalog/templates/catalog/includes/inc_catalog_menu.html
<div class="pricing-header px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
    <h1 class="display-4" align="center">Skystore</h1>
    <p class="lead" align="center">Skystore - найдется все для дома!</p>
</div>
<section class="jumbotron text-center">
    <div class="container">
        <h1 class="jumbotron-heading">У нас самые выгодные цены!</h1>
        <a href="{% url 'catalog:catalog' %}" class="btn btn-primary my-3" style="background: #0062cc">Перейти к покупкам</a>
        <a href="{% url 'blog:home' %}" class="btn btn-secondary my-3" style="background: #0062cc">Главная</a>
        <a href="{% url 'catalog:contacts' %}" class="btn btn-secondary my-3" style="background: #0062cc">Обратная связь</a>
        <a href="{% url 'catalog:category' %}" class="btn btn-secondary my-3" style="background: #0062cc">Категории товаров</a>
    </div>
</section>
<div class="pricing-header px-3 py-3 pt-md-0 pb-md-3 mx-auto text-center">
    <h1 class="display-4">{{ title }}</h1>
</div>

catalog/templates/catalog/includes/inc_product_card.html
{%load tags %}
<div class="col-md-4">
    <div class="card mb-4 box-shadow">
                    <span class="image fit">
                        <img src={% mediapath product.image %} alt={{product.name}} width="350" height="300" id="part1">
                    </span>
        <h5 style="margin: auto; margin-top: 20px">{{product.name}}</h5>
        <div class="card-body">
            {% for version in product.version_set.all %}
                    {% if version.is_active %}
                        <small class="text-muted">Версия: {{version.num_of_version}} ({{ version.title }})</small><br>
                    {% endif %}
                {% endfor %}
            <small class="text-muted">{{product.changed_date}}</small>
            <p class="card-text">{{product.description | truncatechars:100}}</p>
            <h4 style="color: #a41515">Цена: {{product.price}} р.</h4>
            <small class="text-muted">{{product.category}}</small><br>
            {% if product.user %}
                <small class="text-muted">Продавец: {{product.user}}</small>
            {% endif %}
            <div class="d-flex justify-content-between align-items-center">
                <div class="btn-group">
                    <a href="{% url 'catalog:product_items' product.pk %}" class="btn btn-secondary my-3"
                       style="background: #0062cc">Купить</a>

                </div>
            </div>
        </div>
    </div>
</div>