blog/urls.py
from django.urls import path
from django.views.decorators.cache import never_cache
from blog.apps import BlogConfig
from blog.views import *

app_name = BlogConfig.name

urlpatterns = [
    path('', BlogListView.as_view(), name='home'),
    path('<slug:slug>/', BlogDetailView.as_view(), name='blog_detail'),
    path('blog/form/', never_cache(BlogCreateView.as_view()), name='blog_form'),
    path('blog/update/<int:pk>/', never_cache(BlogUpdateView.as_view()), name='blog_update'),
    path('blog/delete/<int:pk>/', BlogDeleteView.as_view(), name='blog_confirm_delete')
]

catalog/urls.py
from django.urls import path
from django.views.decorators.cache import cache_page, never_cache
from catalog.apps import CatalogConfig
from catalog.views import *


app_name = CatalogConfig.name

urlpatterns = [
    path('contacts/',never_cache(ContactCreateView.as_view()), name='contacts'),
    path('catalog/', ProductsListView.as_view(), name='catalog'),
    path('product_items/<int:pk>/', cache_page(60)(ProductDetailView.as_view()), name='product_items'),
    path('product/create/', never_cache(ProductCreateView.as_view()), name='save_product'),
    path('product/update/<int:pk>/', never_cache(ProductUpdateView.as_view()), name='product_form'),
    path('product/update_cutted/<int:pk>/', never_cache(ProductUpdateCuttedView.as_view()), name='product_form_cutted'),
    path('product/is_published/<int:pk>/', change_is_published, name='change_is_published'),
    path('category/', CategoryListView.as_view(), name='category')
]

config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('catalog/', include('catalog.urls', namespace='catalog')),
    path('users/', include('users.urls', namespace='users')),
    path('', include('blog.urls', namespace='blog'))
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

catalog/models.py
from django.db import models

from config import settings

NULLABLE = {'blank': True, 'null': True}


class Category(models.Model):
    name = models.CharField(max_length=150, verbose_name='Наименование')
    description = models.TextField(verbose_name='Описание')

    def __str__(self):
        return f'{self.name}'

    class Meta:
        verbose_name = 'категория'
        verbose_name_plural = 'категории'
        ordering = ('name',)


class Product(models.Model):
    name = models.CharField(max_length=150, verbose_name='Наименование')
    description = models.TextField(verbose_name='Описание')
    image = models.ImageField(upload_to='products/', verbose_name='Изображение', **NULLABLE)
    category = models.ForeignKey(Category, on_delete=models.CASCADE, verbose_name='Категория')
    price = models.IntegerField(verbose_name='Цена за покупку')
    created_date = models.DateField(verbose_name='Дата создания')
    changed_date = models.DateField(verbose_name='Дата последнего изменения')
    is_published = models.BooleanField(default=False, verbose_name='признак активности товара')
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.SET_NULL, **NULLABLE)

    def toggle_is_published(self):
        self.is_published = not self.is_published
        self.save()

    def __str__(self):
        return f'{self.name}'

    class Meta:
        verbose_name = 'продукт'
        verbose_name_plural = 'продукты'
        ordering = ('name',)
        permissions = [
            (
                'set_published_product',
                'Can publish product'
            ),
            (
                'can_edit_description_and_category_product',
                'Can edit description and category product'
            )
        ]


class Contact(models.Model):
    name = models.CharField(max_length=150, verbose_name='Имя пользователя')
    phone = models.CharField(max_length=20, verbose_name='Номер телефона')
    message = models.TextField(verbose_name='Сообщение')

    def __str__(self):
        return f'{self.name} - {self.phone}'

    class Meta:
        verbose_name = 'контакт'
        verbose_name_plural = 'контакты'
        ordering = ('name',)


class Version(models.Model):
    product = models.ForeignKey(Product, on_delete=models.CASCADE, verbose_name='Продукт')
    num_of_version = models.CharField(default=1, verbose_name='Номер версии')
    title = models.CharField(max_length=150, verbose_name='Название версии', **NULLABLE)

    is_active = models.BooleanField(default=True, verbose_name='признак текущей версии')

    def __str__(self):
        return f'{self.title} - {self.num_of_version} ({self.product})'

    class Meta:
        verbose_name = 'версия'
        verbose_name_plural = 'версии'

catalog/forms.py
from django import forms

from catalog.models import *

FORBIDDEN_WORDS = ['казино', 'криптовалюта', 'крипта', 'биржа', 'дешево', 'бесплатно', 'обман', 'полиция',
                   'радар']


class FormStyleMixin:
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'form-control'


class ProductForm(FormStyleMixin, forms.ModelForm):
    class Meta:
        model = Product
        exclude = ('user', 'is_published')

    def clean_name(self):
        cleaned_data = self.cleaned_data['name']
        if cleaned_data.lower() in FORBIDDEN_WORDS:
            raise forms.ValidationError(f"Нельзя вносить слово {cleaned_data}, замените его на другое")
        return cleaned_data

    def clean_description(self):
        cleaned_data = self.cleaned_data['description']
        if cleaned_data.lower() in FORBIDDEN_WORDS:
            raise forms.ValidationError(f"Нельзя вносить слово {cleaned_data}, замените его на другое")
        return cleaned_data


class ProductFormCutted(ProductForm, FormStyleMixin, forms.ModelForm):
    class Meta:
        model = Product
        fields = ('description', 'category')


class VersionForm(FormStyleMixin, forms.ModelForm):
    class Meta:
        model = Version
        fields = ('product', 'num_of_version', 'title',)

catalog/views.py
from django.contrib.auth.decorators import permission_required
from django.contrib.auth.mixins import PermissionRequiredMixin, LoginRequiredMixin
from django.forms import inlineformset_factory
from django.shortcuts import get_object_or_404, redirect
from django.urls import reverse_lazy, reverse
from django.views import generic

from catalog.forms import ProductForm, VersionForm, ProductFormCutted
from catalog.models import Product, Contact, Version, Category
from catalog.services.cashe import get_cache_categories


class CategoryListView(generic.ListView):
    model = Category
    queryset = get_cache_categories()

    def get_context_data(self, **kwargs):
        context_data = super().get_context_data(**kwargs)
        context_data['product_list'] = Product.objects.all()
        context_data['title'] = "Категории товаров"
        return context_data


class ProductsListView(generic.ListView):
    model = Product
    extra_context = {
        "title": "Каталог товаров"
    }


class ProductDetailView(generic.DetailView):
    model = Product

    def get_context_data(self, **kwargs):
        context_data = super().get_context_data(**kwargs)
        context_data['title'] = context_data['product']
        return context_data


class ContactCreateView(generic.CreateView):
    model = Contact
    fields = ('name', 'phone', 'message')


class ProductCreateView(LoginRequiredMixin, generic.CreateView):
    model = Product
    extra_context = {
        "title": "Внести новый товар"
    }
    form_class = ProductForm
    success_url = reverse_lazy('catalog:catalog')

    def form_valid(self, form):
        self.object = form.save()
        self.object.user = self.request.user
        self.object.save()
        return super().form_valid(form)


class ProductUpdateCuttedView(PermissionRequiredMixin, generic.UpdateView):
    model = Product
    template_name = 'catalog/product_form.html'
    form_class = ProductFormCutted
    permission_required = 'catalog.can_edit_description_and_category_product'

    def get_success_url(self):
        return reverse('catalog:product_items', kwargs={'pk': self.object.pk})


class ProductUpdateView(generic.UpdateView):
    model = Product
    template_name = 'catalog/product_form_with_formset.html'
    form_class = ProductForm

    def get_context_data(self, **kwargs):
        context_data = super().get_context_data(**kwargs)
        VersionFormset = inlineformset_factory(Product, Version, form=VersionForm, extra=1)

        if self.request.method == 'POST':
            context_data['formset'] = VersionFormset(self.request.POST, instance=self.object)

        else:
            context_data['formset'] = VersionFormset(instance=self.object)

        return context_data

    def form_valid(self, form):
        context_data = self.get_context_data()
        formset = context_data['formset']
        self.object = form.save()
        if formset.is_valid():
            formset.instance = self.object
            formset.save()
        return super().form_valid(form)

    def get_success_url(self):
        return reverse('catalog:product_items', kwargs={'pk': self.object.pk})


@permission_required('catalog.set_published_product')
def change_is_published(request, pk):
    product_item = get_object_or_404(Product, pk=pk)
    product_item.toggle_is_published()
    return redirect(reverse('catalog:product_items', args=[product_item.pk]))

catalog/templates/catalog/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Skystore</title>
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <script src="{% static 'js/bootstrap.min.js' %}"></script>
</head>
<body>
{% include 'catalog/includes/inc_catalog_address.html' %}

{%include 'catalog/includes/inc_catalog_menu.html' %}
<div class="album py-5 bg-light">
    <div class="container">
        <div class="row">
            {% block content %}
            {% endblock %}
        </div>
    </div>
</div>
{% include 'catalog/includes/inc_catalog_footer.html' %}
<script src="{% static 'js/bootstrap.min.js' %}"></script>
</body>
</html>

catalog/templates/catalog/category_list.html
{% extends 'catalog/base.html' %}

{% block content %}
    {% for category in category_list %}
        <div class="card">
            <div class="card-header">
                <div class="table text-center">{{ category }}</div>
            </div>
            <div class="card-body">
                {{ category.description }}
            </div>
            <div class="card-footer">
                {% for product in product_list %}

                    {% if product.category == category %}
                        <div class="table text-center">
                            <a style="background: white; color: black" class="btn-success"
                               href="{% url 'catalog:product_items' product.pk %}">{{ product }}</a>
                            <br>
                        </div>
                    {% endif %}

                {% endfor %}
            </div>
        </div>
    {% endfor %}

{% endblock %}

catalog/templates/catalog/contact_form.html
{% extends 'catalog/base.html' %}

{% block content %}
<div class="container">
    <div class="row text-start">
        <div class="col-lg-6" style="margin: auto">
            <div class="card mb-2 box-shadow">
                <form method="post">
                    {% csrf_token %}
                    <div class="card-header">
                        <h4 class="my-0 font-weight-normal">Связаться с нами</h4>
                    </div>
                    <div class="card-body">
                        <div class="mb-3">
                            <label for="name">Имя</label>
                            <input type="text" name="name" class="form-control" id="name" placeholder="Ваше имя"
                                   required>
                        </div>
                        <div class="mb-3">
                            <label for="phone">Номер телефона (с кодом) </label>
                            <input type="text" name="phone" class="form-control" id="phone"
                                   placeholder="Контактный телефон" required>
                        </div>
                        <div class="mb-3">
                            <label for="message">Сообщение</label>
                            <textarea type="text" name="message" class="form-control" id="message"
                                      placeholder="Сообщение" required></textarea>
                        </div>
                        <button type="submit" class="btn btn-lg btn-block btn-outline-primary">Оставить заявку</button>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>
{% endblock %}

catalog/templates/catalog/product_detail.html
{% extends 'catalog/base.html' %}
{% block content %}
    {% load tags %}
    <div class="container">
        <div class="col-md-6">
            <div class="card flex-md-row mb-5 box-shadow h-md-450">
                <div class="card-body d-flex flex-column align-items-start">
                    <small class="d-inline-block mb-2 text-primary">{{ product.category }}</small>
                    <h3 class="mb-0">
                        <a class="text-dark" href="#">Цена: {{ product.price }} р</a>
                    </h3>
                    <small class="mb-1 text-muted">{{ product.created_date }}</small>
                    <p class="card-text mb-auto">{{ product.description }}</p>

                    {% if user == product.user or user.is_superuser %}
                        <a href="{% url 'catalog:product_form' product.pk %}" class="btn btn-secondary my-3"
                           style="background: green">Изменить</a>
                    {% elif perms.catalog.can_edit_description_and_category_product %}
                        <a href="{% url 'catalog:product_form_cutted' product.pk %}" class="btn btn-secondary my-3"
                           style="background: green">Изменить</a>
                    {% endif %}

                    {% if perms.catalog.set_published_product %}

                        {% if product.is_published %}
                            <a href="{% url 'catalog:change_is_published' product.pk %}" class="btn btn-secondary my-3"
                               style="background: red">Удалить</a>
                        {% else %}
                            <a href="{% url 'catalog:change_is_published' product.pk %}" class="btn btn-secondary my-3"
                               style="background: red">Опубликовать</a>
                        {% endif %}

                    {% endif %}
                </div>
                <img src="{% mediapath product.image %}" alt={{ product.name }} width="350" height="300" id="part1">
            </div>
        </div>
    </div>
    <div>
        <a href="{% url 'catalog:catalog' %}" class="btn btn-secondary my-3"
           style="background: #0062cc">Назад</a>
    </div>
{% endblock %}

catalog/templates/catalog/product_form.html
{% extends 'catalog/base.html' %}

{% block content %}
    <form class="obratnuj-zvonok" autocomplete="off" method='post'>
        {% csrf_token %}
        <div class="container">
            {{ form.as_p }}
            {% if perms.catalog.can_edit_description_and_category_product %}
                <input type="submit" class="btn btn-success" value="Изменить">
            {% endif %}
        </div>
    </form>
{% endblock %}

catalog/templates/catalog/product_form_with_formset.html
{% extends 'catalog/base.html' %}

{% block content %}
    <div class="col">
        <form class="row" autocomplete="off" method='post'>
            <div class="col-6">
                <div class="card">
                    <div class="card-header">
                        Добавить товар
                    </div>
                    <div class="card-body">
                        {% csrf_token %}
                        {{ form.as_p }}
                            <input type="submit" class="btn btn-success" value="Изменить">
                    </div>
                </div>
            </div>
            {% if user == product.user %}
            <div class="col-6">
                <div class="card">
                    <div class="card-header">
                        Версии
                    </div>
                    <div class="card-body">
                        <table class="table">
                            {{ formset.management_form }}
                            {% for form in formset.forms %}
                                <tr class="subject-form">
                                    <td>{{ form.as_p }}</td>
                                </tr>
                            {% endfor %}
                        </table>
                    </div>
                </div>
            {% endif %}
        </form>
    </div>
{% endblock %}

catalog/templates/catalog/product_list.html
{% extends 'catalog/base.html' %}

{% block content %}
    {% for product in product_list %}
        {% include 'catalog/includes/inc_product_card.html' %}
    {% endfor %}
    <div class="container">
        {% if user.is_authenticated %}
            <a href="{% url 'catalog:save_product' %}" class="btn btn-secondary my-3"
               style="background: darkgreen">Создать</a>
        {% endif %}
    </div>
{% endblock %}